# -*- coding: utf-8 -*-
"""Submission Proyek 1 Machine Learning Terapan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hMyWRRADIusFPIIJw9lsz01Q1iW1SaL3

# Proyek Pertama Machine Learning Terapan: Drug Consumption
- **Nama:** Salma Zhafira Muchtar
- **Email:** zhafirasalmam@gmail.com
- **ID Dicoding:** MC011D5X2034

# **Laporan Proyek Machine Learning - Salma Zhafira Muchtar**

# **Project Overview**

## **Latar Belakang**

Penggunaan zat psikoaktif, baik yang legal maupun ilegal, merupakan isu yang kompleks dan multidimensional yang dipengaruhi oleh berbagai faktor psikologis dan demografi. Karakteristik kepribadian, impulsivitas, dan sensasi mencari pengalaman (sensasi mencari) adalah komponen penting yang harus dikaji secara menyeluruh untuk memahami perilaku konsumsi zat tersebut ([Fernández-Suárez et al., 2024](https://www.mdpi.com/2076-3425/14/5/449); [Sagepub, 2024)](https://journals.sagepub.com/doi/10.1177/09727531241274098)). Profil kepribadian tertentu, seperti tingkat neurotisisme yang tinggi, extraversion, dan kesadaran (conscientiousness) yang rendah, telah dikaitkan dengan risiko lebih besar dalam penggunaan zat terlarang maupun alkohol  ([Volkow et al., 2023](https://pmc.ncbi.nlm.nih.gov/articles/PMC10168177/)).

Metode komputasi seperti Machine Learning semakin banyak digunakan untuk memahami dan memprediksi perilaku konsumsi zat berdasarkan demografi dan psikologi ([Castaneda et al., 2022](https://www.idescat.cat/sort/sort471/47.1.1.Castaneda-etal.pdf)). Analisis data dapat digunakan untuk mengungkap berbagai pola dan hubungan yang kompleks secara lebih sistematis dan objektif. Hal ini berkontribusi signifikan dalam pengambilan keputusan, khususnya dalam strategi pencegahan dan intervensi dini ([Tan & Fauzi, 2023](https://www.svedbergopen.com/files/1698407561_3_IJDSBDA202313011740NZ_(p_45-57).pdf))

Sumber data yang lengkap untuk menganalisis hubungan tersebut adalah Dataset Konsumsi Obat (Quantified), yang dikumpulkan oleh Fehrman et al. (2017) dan tersedia di Perpustakaan Pembelajaran Mesin UCI ([Fehrman et al., 2017](https://arxiv.org/abs/1506.06297)). Dataset ini berisi data dari 1885 responden yang mencakup 12 atribut utama, antara lain skor kepribadian berdasarkan model lima faktor (NEO-FFI-R), skor impulsivitas (BIS-11), sensasi mencari pengalaman (ImpSS), serta variabel demografi seperti usia, jenis kelamin, tingkat pendidikan, negara, dan etnisitas ([UCI Machine Learning Repository](https://archive.ics.uci.edu/dataset/373/drug+consumption+quantified)). Selain itu, data juga mencakup informasi tentang frekuensi penggunaan delapan belas jenis psikoaktif, termasuk alkohol, amfetamin, benzodiazepin, ganja, kokain, heroin, dan satu substansi yang tidak nyata untuk mengidentifikasi klaim palsu ([Fehrman et al., 2017](https://arxiv.org/abs/1506.06297)).

Dengan tujuh kategori mulai dari "Never Used" hingga "Used in Last Day", setiap responden melaporkan berapa kali mereka menggunakan zat tersebut. Dataset ini memungkinkan klasifikasi status pengguna dan analisis risiko konsumsi berdasarkan karakteristik psikologis dan demografis ([Fehrman et al., 2017](https://arxiv.org/abs/1506.06297)). Dengan demikian, dataset ini sangat berguna untuk mengembangkan model prediktif dan memahami faktor-faktor yang memengaruhi perilaku penggunaan zat psikoaktif, termasuk menemukan faktor kepribadian dan demografi yang paling berpengaruh terhadap risiko konsumsi alkohol dan zat lain ([Fehrman et al., 2017](https://arxiv.org/abs/1506.06297)).

Melalui penelitian berbasis data ini, diharapkan diperoleh pemahaman yang lebih baik mengenai faktor risiko yang memengaruhi konsumsi zat, serta kontribusi penting untuk bidang psikologi klinis, kebijakan kesehatan masyarakat, dan upaya rehabilitasi.

# **Business Understanding**

## **Problem Statements**

Berdasarkan latar belakang dan kajian pustaka mengenai konsumsi zat serta hubungan dengan faktor demografi dan kepribadian, maka rumusan masalah dalam penelitian ini adalah sebagai berikut:

1. Bagaimana hubungan antara tingkat impulsivitas dan sensasi mencari pengalaman (sensation seeking) dengan frekuensi konsumsi zat psikoaktif?

2. Bagaimana model prediktif dapat digunakan untuk memprediksi frekuensi konsumsi zat psikoaktif berdasarkan karakteristik psikologis (big five personality traits) dan demografis?

## **Goals**

Berdasarkan rumusan masalah yang telah dijelaskan, penelitian ini bertujuan untuk:

1. Menganalisis hubungan antara tingkat impulsivitas dan sensasi mencari pengalaman dengan frekuensi konsumsi zat psikoaktif.

2. Membangun model prediksi untuk memprediksi frekuensi konsumsi zat psikoaktif berdasarkan variabel psikologis (big five personality traits) dan demografis.

## **Solution Statements**

Berdasarkan tujuan yang telah dirumuskan, solusi yang diajukan untuk mencapai goals tersebut meliputi dua pendekatan utama sebagai berikut:

1. Membangun model prediksi menggunakan algoritma regresi seperti Linear Regression dan Random Forest Regressor untuk memprediksi frekuensi konsumsi zat berdasarkan tingkat impulsivitas, sensasi mencari pengalaman (sensation seeking), fitur psikologis (big five personality traits) dan demografi.

2. Melakukan hyperparameter tuning pada model terbaik serta mengevaluasi performa model dengan metrik seperti MAE, RMSE, dan R².

# **Data Understanding**

## **Data Loading**
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_csv("/content/drug_consumption.data", sep=",", header=None)

# Simpan ke file CSV
df.to_csv("data.csv", index=False)

print("Konversi selesai, file CSV berhasil dibuat.")

import pandas as pd

# Baca file CSV
df = pd.read_csv('data.csv')

# Tampilkan beberapa baris pertama
print(df.head())

new_column_names = [
    'ID',
    'Age',
    'Gender',
    'Education',
    'Country',
    'Ethnicity',
    'Nscore',      # Neuroticism
    'Escore',      # Extraversion
    'Oscore',      # Openness
    'Ascore',      # Agreeableness
    'Cscore',      # Conscientiousness
    'Impulsive',   # Impulsivity
    'SS',          # Sensation Seeking
    'Alcohol',
    'Amphetamines',
    'Amyl Nitrite',
    'Benzodiazepines',
    'Caffeine',
    'Cannabis',
    'Chlorpromazine',
    'Cocaine',
    'Crack',
    'Ecstasy',
    'Heroin',
    'Ketamine',
    'Legal Highs',
    'LSD',
    'Methadone',
    'Magic Mushrooms',
    'Nicotine',
    'Semer',
    'VSA'
]
df.columns = new_column_names

print(df.columns.tolist())
df

import pandas as pd

age_map = {
    -0.95197: '18-24',
    -0.07854: '25-34',
     0.49788: '35-44',
     1.09449: '45-54',
     1.82213: '55-64',
     2.59171: '65+'
}
gender_map = {
    0.48246: 'Female',
   -0.48246: 'Male'
}
education_map = {
    -2.43591: 'Left school before 16 years',
    -1.73790: 'Left school at 16 years',
    -1.43719: 'Left school at 17 years',
    -1.22751: 'Left school at 18 years',
    -0.61113: 'Some college/university, no degree',
    -0.05921: 'Professional certificate/diploma',
     0.45468: 'University degree',
     1.16365: 'Masters degree',
     1.98437: 'Doctorate degree'
}
country_map = {
    -0.09765: 'Australia',
     0.24923: 'Canada',
    -0.46841: 'New Zealand',
    -0.28519: 'Other',
     0.21128: 'Republic of Ireland',
     0.96082: 'UK',
    -0.57009: 'USA'
}
ethnicity_map = {
    -0.50212: 'Asian',
    -1.10702: 'Black',
     1.90725: 'Mixed-Black/Asian',
     0.12600: 'Mixed-White/Asian',
    -0.22166: 'Mixed-White/Black',
     0.11440: 'Other',
    -0.31685: 'White'
}

# Replace langsung isi kolom asli
df['Age'] = df['Age'].replace(age_map)
df['Gender'] = df['Gender'].replace(gender_map)
df['Education'] = df['Education'].replace(education_map)
df['Country'] = df['Country'].replace(country_map)
df['Ethnicity'] = df['Ethnicity'].replace(ethnicity_map)
df

"""Penelitian ini menggunakan dataset Drug Consumption (Quantified) yang diperoleh dari [UCI Machine Learning Repository](https://archive.ics.uci.edu/dataset/373/drug+consumption+quantified), dan pertama kali dipublikasikan oleh Fehrman et al. (2017). Dataset ini dikumpulkan melalui survei daring terhadap 1.885 responden dewasa, yang berasal dari berbagai negara, terutama kawasan Eropa dan Amerika Utara.

Setelah dimuat ke dalam lingkungan Python, dataset ini awalnya tersedia dalam format .data (plaintext), kemudian dikonversi ke format .csv (comma-separated values) untuk mempermudah proses interpretasi, visualisasi, serta analisis menggunakan perangkat lunak statistik dan machine learning berbasis Python. Selain itu, nama-nama kolom yang semula berupa angka (1, 2, 3, dan seterusnya) telah diubah menjadi label fitur yang lebih deskriptif dan informatif, sesuai dengan dokumentasi asli, guna meningkatkan keterbacaan dan kemudahan analisis. Lebih lanjut, nilai-nilai numerik pada beberapa variabel kategorikal seperti usia, jenis kelamin, pendidikan, dan etnis diinterpretasikan ulang ke dalam bentuk label kategori yang representatif—misalnya, nilai -0.95197 pada variabel usia diubah menjadi '18-24', dan nilai 0.48246 pada variabel jenis kelamin menjadi 'Female'. Transformasi ini dilakukan agar data lebih mudah dianalisis dan dipahami, terutama dalam konteks visualisasi maupun pemodelan prediktif.

Secara keseluruhan, dataset ini terdiri dari 1.885 baris, di mana setiap baris merepresentasikan satu individu. Terdapat 32 kolom yang mencakup atribut psikologis, demografis, serta informasi terkait penggunaan 18 jenis zat psikoaktif. Setiap entri dalam dataset ini menggambarkan kombinasi dari karakteristik kepribadian, latar belakang demografi, dan pola konsumsi zat yang dilaporkan oleh masing-masing responden.

Sumber Data : [Drug Consumption (Quantified)](https://archive.ics.uci.edu/dataset/373/drug+consumption+quantified)

**Berikut penjelasan fitur berdasarkan kategori data dalam dataset drug consumption:**

1. **ID**
   Variabel unik yang digunakan untuk mengidentifikasi setiap responden.

2. **Age (Usia)**
   Kelompok umur peserta dalam kategori 18-24, 25-34, 35-44, 45-54, 55-64, dan 65+.

3. **Gender (Jenis Kelamin)**
   Jenis kelamin peserta, yaitu laki-laki dan perempuan.

4. **Education (Tingkat Pendidikan)**
   Tingkat pendidikan terakhir yang ditempuh peserta dalam kategori: sekolah dasar, sekolah menengah pertama, sekolah menengah atas, diploma, sarjana, pascasarjana.

5. **Country (Negara Tempat Tinggal)**
   Negara tempat tinggal peserta.

6. **Ethnicity (Etnis)**
   Kelompok etnis peserta.

---

**Big Five Personality Traits**
Kelima dimensi kepribadian ini digunakan untuk menggambarkan sifat dan karakter seseorang secara umum:

7. **Neuroticism (Nscore)**
   Mengukur tingkat kecenderungan mengalami emosi negatif seperti cemas, marah, dan depresi.

8. **Extraversion (Escore)**
   Mengukur tingkat keaktifan sosial, energi, dan kecenderungan mencari interaksi sosial.

9. **Openness to Experience (Oscore)**
   Mengukur tingkat rasa ingin tahu, imajinasi, dan keterbukaan terhadap pengalaman baru.

10. **Agreeableness (Ascore)**
    Mengukur tingkat sifat ramah, empati, dan kepercayaan kepada orang lain.

11. **Conscientiousness (Cscore)**
    Mengukur tingkat disiplin, tanggung jawab, dan ketelitian.

---

**Skor Tambahan Psikologis**

12. **Impulsivity (Impulsive)**
    Mengukur kecenderungan bertindak tanpa berpikir matang terlebih dahulu.

13. **Sensation Seeking (SS)**
    Mengukur kecenderungan mencari pengalaman dan sensasi baru yang intens.

---

**Variabel konsumsi zat (setiap variabel mewakili jenis zat):**
Nilai variabel ini bersifat kategorikal dan menggambarkan riwayat penggunaan zat oleh responden dengan kategori:

* CL0: Never (Tidak pernah menggunakan)
* CL1: Used over a decade ago (Pernah menggunakan lebih dari 10 tahun yang lalu)
* CL2: Used in last decade (Pernah menggunakan dalam 10 tahun terakhir)
* CL3: Used in last year (Pernah menggunakan dalam 1 tahun terakhir)
* CL4: Used in last month (Pernah menggunakan dalam 1 bulan terakhir)
* CL5: Used in last week (Pernah menggunakan dalam 1 minggu terakhir)
* CL6: Used in last day (Pernah menggunakan dalam 1 hari terakhir)

14. **Alcohol**
    Status penggunaan alkohol oleh peserta.

15. **Amphetamines**
    Status penggunaan amfetamin.

16. **Amyl Nitrite**
    Status penggunaan amil nitrit.

17. **Benzodiazepines**
    Status penggunaan benzodiazepin.

18. **Caffeine**
    Status konsumsi kafein.

19. **Cannabis**
    Status penggunaan ganja.

20. **Chlorpromazine**
    Status penggunaan klorpromazin.

21. **Cocaine**
    Status penggunaan kokain.

22. **Crack**
    Status penggunaan crack.

23. **Ecstasy**
    Status penggunaan ekstasi.

24. **Heroin**
    Status penggunaan heroin.

25. **Ketamine**
    Status penggunaan ketamin.

26. **Legal Highs**
    Status penggunaan zat psikoaktif legal.

27. **LSD**
    Status penggunaan LSD.

28. **Methadone**
    Status penggunaan metadon.

29. **Magic Mushrooms**
    Status penggunaan jamur psikedelik.

30. **Nicotine**
    Status konsumsi nikotin.

31. **Semer**
    Status penggunaan semer.

32. **VSA (Volatile Substance Abuse)**
    Status penyalahgunaan zat volatil.
"""

df.drop(columns='ID', inplace=True)
df

"""Kolom ID dihapus dari dataset karena tidak mengandung informasi yang relevan untuk proses analisis. Kolom ini hanya berfungsi sebagai penanda unik tiap baris, namun tidak memberikan kontribusi terhadap pemahaman pola data, analisis statistik, maupun pemodelan machine learning. Oleh karena itu, kolom ini dihilangkan agar tidak mengganggu atau membebani proses analisis selanjutnya."""

# Jumlah baris dan kolom
print("Jumlah baris dan kolom:")
print(df.shape)

# Cek 5 data teratas
print("\nLima data teratas:")
print(df.head())

# Informasi umum tentang tipe data dan missing values
print("\nInformasi tipe data dan non-null values:")
print(df.info())

"""* Lima data teratas ditampilkan untuk memberikan gambaran awal terhadap bentuk dan isi dataset setelah dilakukan transformasi label pada variabel demografis. Terlihat bahwa kolom seperti Age, Gender, Education, Country, dan Ethnicity kini telah menggunakan label kategorikal yang lebih deskriptif.

* Dari hasil fungsi df.info(), diketahui bahwa tidak terdapat missing values dalam dataset ini, karena seluruh kolom memiliki 1.885 nilai non-null.

* Tipe data yang digunakan terdiri dari float64 untuk variabel numerik (seperti skor kepribadian,  impulsivitas, dan Sensation seeking), serta object untuk variabel kategorikal (seperti variabel demografi dan status penggunaan zat).

Hal ini menunjukkan bahwa data tidak memerlukan penanganan nilai hilang.
"""

df.describe()

"""Hasil describe() menunjukkan bahwa seluruh variabel numerik memiliki 1.885 data, tanpa missing values. Skor kepribadian, impulsivitas, dan sensation seeking sudah dalam bentuk z-score (mean ≈ 0, std ≈ 1), menandakan data telah dinormalisasi. Nilai minimum dan maksimum yang cukup ekstrim mengindikasikan potensi outlier. Distribusi terlihat simetris (median ≈ 0)

## **Pemeriksaan Outlier dan Penanganannya**
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Ambil semua kolom numerik dari dataframe
numerical_vars = df.select_dtypes(include=['float64']).columns.tolist()

# Visualisasi outlier sebelum penanganan
fig, axes = plt.subplots(nrows=1, ncols=len(numerical_vars), figsize=(5 * len(numerical_vars), 5))
fig.suptitle('Boxplot Sebelum Penanganan Outlier (Variabel Numerik)', fontsize=16)

if len(numerical_vars) == 1:
    axes = [axes]

for i, col in enumerate(numerical_vars):
    sns.boxplot(y=df[col], ax=axes[i], color='lightpink')
    axes[i].set_title(col)

plt.tight_layout()
plt.show()

"""Sebelum dilakukan penanganan, visualisasi boxplot pada lima dimensi skor kepribadian (Nscore, Escore, Oscore, Ascore, dan Cscore) dan impulsivitas menunjukkan adanya sejumlah outlier. Hal ini terlihat dari adanya titik-titik di luar rentang whisker pada boxplot. Meskipun data telah dinormalisasi, nilai-nilai ekstrem masih tetap dapat terdeteksi karena proses normalisasi tidak menghilangkan outlier."""

from scipy.stats import zscore
import matplotlib.pyplot as plt
import seaborn as sns

# Kolom numerik dari dataframe
numerical_vars = df.select_dtypes(include=['float64']).columns.tolist()

# Penanganan Outlier (Z-score > 3 diganti median)
for col in numerical_vars:
    z_scores = zscore(df[col])
    median_val = df[col].median()
    df[col] = df[col].where(abs(z_scores) <= 3, median_val)

# Visualisasi setelah penanganan outlier
fig, axes = plt.subplots(1, len(numerical_vars), figsize=(5 * len(numerical_vars), 5))
fig.suptitle('Boxplot Sesudah Penanganan Outlier (Variabel Numerik)', fontsize=16)

if len(numerical_vars) == 1:
    axes = [axes]

for i, col in enumerate(numerical_vars):
    sns.boxplot(y=df[col], ax=axes[i], color='lightgreen')
    axes[i].set_title(col)

plt.tight_layout()
plt.show()

"""Penanganan dilakukan menggunakan metode Z-score, di mana data dengan nilai Z lebih dari 3 dianggap sebagai outlier. Alih-alih menghapus data tersebut, nilai outlier digantikan dengan nilai median pada masing-masing kolom. Pendekatan ini dipilih karena:

- Jumlah data cukup terbatas (n = 1885) sehingga menghapus baris yang mengandung outlier berisiko mengurangi variasi dan informasi dalam data.

- Mengganti outlier dengan median tetap menjaga ukuran sampel dan mencegah hilangnya pola yang mungkin penting untuk analisis selanjutnya.

- Median lebih robust terhadap outlier, sehingga dapat mengurangi distorsi tanpa menggeser distribusi secara ekstrem.

Setelah penanganan, boxplot menunjukkan distribusi yang lebih merata dan jumlah outlier yang jauh berkurang, terkhusus untuk Impulsive yang tidaak terdapat outlier lagi. Hal ini menunjukkan bahwa proses penggantian berhasil mereduksi nilai-nilai ekstrem tanpa mengubah pola data secara signifikan.

## **Univariate Analysis**
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Untuk memperjelas tampilan plot
sns.set(style="whitegrid")

import math
import matplotlib.pyplot as plt
import seaborn as sns

# Kolom numerik
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

# Jumlah baris & kolom
cols = 3
rows = math.ceil(len(numeric_cols) / cols)

# Ukuran figure
plt.figure(figsize=(cols * 3, rows * 2))

for i, col in enumerate(numeric_cols):
    plt.subplot(rows, cols, i + 1)
    sns.histplot(df[col], kde=True, bins=30, color='skyblue')
    plt.title(col, fontsize=10)
    plt.xlabel('')
    plt.ylabel('')
    plt.tight_layout()

plt.tight_layout()
plt.show()

"""Gambar di atas menampilkan histogram dengan kurva Kernel Density Estimation (KDE) untuk setiap variabel numerik dalam dataset, sebagian besar variabel kepribadian (Nscore hingga Cscore) menunjukkan pola distribusi yang cukup simetris dan menyerupai distribusi normal, yang sesuai dengan karakteristik data yang telah dinormalisasi. Sedangkan variabel Impulsive dan Sensation Seeking (SS) terlihat sedikit menyimpang dari normal, dengan bentuk yang lebih miring (skewed), menunjukkan adanya variasi atau ketidakseimbangan dalam persebaran nilai responden."""

import math
import matplotlib.pyplot as plt
import seaborn as sns

# Kolom kategorikal
categorical_cols = df.select_dtypes(include=['object']).columns

# Frekuensi masing-masing kategori
for col in categorical_cols:
    print(f"\nDistribusi nilai untuk kolom: {col}")
    print(df[col].value_counts())

# Layout dan ukuran plot
cols = 3
rows = math.ceil(len(categorical_cols) / cols)

plt.figure(figsize=(cols * 5, rows * 4))

for i, col in enumerate(categorical_cols):
    plt.subplot(rows, cols, i + 1)
    sns.countplot(data=df, x=col, order=df[col].value_counts().index, palette='pastel')
    plt.title(col, fontsize=10)
    plt.xticks(rotation=45, ha='right')
    plt.xlabel('')
    plt.ylabel('')

plt.tight_layout()
plt.show()

"""Visualisasi barplot di atas menampilkan distribusi frekuensi dari seluruh variabel kategorikal yang ada dalam dataset.
#### 1. Age

- Mayoritas responden berusia 18–24 tahun, diikuti oleh 25–34 tahun.
- Kelompok usia di atas 55 tahun jauh lebih sedikit.

#### 2. Gender

- Komposisi hampir seimbang antara laki-laki dan perempuan.

#### 3. Education

- Mayoritas berpendidikan tinggi, terutama some college dan university degree.
- Pendidikan rendah (<18 tahun) dan doktoral jumlahnya kecil.

#### 4. Country

- Responden paling banyak berasal dari UK dan USA
- Negara lain seperti Australia, Ireland, dan New Zealand cukup kecil proporsinya.

#### 5. Ethnicity

- Mayoritas adalah etnis White, kelompok etnis lain relatif sedikit.

#### 6. Penggunaan Obat (per Zat)

- Caffeine dan Alcohol adalah dua zat yang paling sering digunakan oleh responden.

  - Caffeine didominasi oleh kategori CL6 (Used in last day) sebanyak 1385 orang dan CL5 (Used in last week) sebanyak 273 orang.
  - Alcohol juga tinggi, dengan dominasi di CL5 (Used in last week) sebanyak 759 orang dan CL6 (Used in last day) sebanyak 505 orang.

- Cannabis dan Nicotine menunjukkan pola distribusi yang relatif merata:

  - Keduanya memiliki pengguna yang tersebar di hampir semua kategori dari CL0 sampai CL6.
  - Cannabis tertinggi di CL6 (463) dan CL0 (413), menandakan sebagian besar responden rutin menggunakan, sebagian lainnya tidak pernah.
  - Nicotine tertinggi di CL6 (610) dan CL0 (428), menunjukkan tren serupa.

- Beberapa zat seperti Amphetamines, Benzodiazepines, Ecstasy, LSD, Legal Highs, dan Magic Mushrooms juga cukup bervariasi, namun jumlah terbesar tetap berada di CL0 (tidak pernah menggunakan).

- Heroin, Semer, dan Crack menunjukkan dominasi kuat di CL0:

  - Heroin: 1605 responden di CL0
  - Semer: 1877 responden di CL0
   Crack: 1627 responden di CL0
    
    Hal ini mengindikasikan bahwa sebagian besar responden tidak memiliki pengalaman dengan zat-zat tersebut.

## **Multivariate Analysis**

### **Korelasi antar fitur numerik**
"""

# Korelasi antar fitur numerik
plt.figure(figsize=(12, 10))
corr_matrix = df[numeric_cols].corr()

sns.heatmap(corr_matrix, annot=True, fmt=".2f", cmap='coolwarm', square=True, cbar_kws={'shrink': 0.8})
plt.title('Correlation Heatmap (Numerical Features)', fontsize=16)
plt.show()

"""Visualisasi Heatmap di atas menunjukkan korelasi antara variabel numerik sebagai berikut.

**1. Korelasi Tinggi:**
- Impulsivity (Impulsive) & Sensation Seeking (SS): korelasi 0.62 → makin impulsif seseorang, makin tinggi Sensation Seeking-nya.

- Openness to Experience (Oscore) & Sensation Seeking (SS): korelasi 0.42 → orang dengan openness tinggi cenderung lebih sensation seeking.

- Extraversion (Escore) & Conscientiousness (Cscore): korelasi 0.30 → ekstrovert sedikit cenderung lebih conscientious.

**2. Korelasi Negatif:**
- Neuroticism (Nscore) & Extraversion (Escore): -0.43 → neurotik cenderung kurang ekstrovert.

- Neuroticism (Nscore) & Conscientiousness (Cscore): -0.38 → neurotik cenderung tidak conscientious.

- Conscientiousness (Cscore) & Impulsivity (Impulsive): -0.33 → makin conscientious, makin tidak impulsif.

- Conscientiousness (Cscore) & Sensation Seeking (SS): -0.24 → conscientious rendah cenderung lebih sensation seeking.

**3. Korelasi Lemah:**
- Korelasi antar sebagian besar skor (Openness to Experience (Oscore) dan Agreeableness (Ascore)) tergolong lemah atau tidak signifikan secara praktis.

### **Personality Traits vs Drug Use Alcohol**
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd


# Define personality traits and category order
personality = ['Nscore', 'Escore', 'Oscore', 'Ascore', 'Cscore']
alcohol_order = ['CL0', 'CL1', 'CL2', 'CL3', 'CL4', 'CL5', 'CL6']

# Create point plots for each personality trait vs Alcohol use
plt.figure(figsize=(18, 10))
for i, feature in enumerate(personality):
    plt.subplot(2, 3, i + 1)
    sns.pointplot(x='Alcohol', y=feature, data=df, order=alcohol_order, palette='Set2', errorbar='sd')
    plt.title(f'{feature} vs Alcohol Usage')
    plt.xticks(rotation=45)
    plt.tight_layout()

plt.suptitle('Personality Traits vs Alcohol Use Categories (Mean ± SD)', fontsize=16, y=1.02)
plt.show()

"""Berdasarkan visualisasi pointplot antara skor kepribadian (Big Five) dengan kategori penggunaan alkohol (CL0–CL6), ditemukan beberapa pola yang cukup konsisten:

#### 1. Nscore (Neuroticism)

- Titik cenderung di bawah 0 untuk CL0–CL1 (tidak atau jarang konsumsi), naik sedikit di CL2–CL4, lalu datar.
- Pengguna alkohol ringan cenderung punya skor neurotik lebih rendah, tapi tidak ada tren jelas meningkat untuk pengguna berat.

#### 2. Escore (Extraversion)

- Skor cenderung negatif di CL2–CL3, lalu kembali naik di CL5.
- Ada penurunan sementara untuk peminum sedang, tapi pengguna rutin cenderung lebih ekstrovert.

#### 3. Oscore (Openness)

- Rata-rata skor relatif stabil, sedikit naik di CL4–CL6.
- Tidak ada pola ekstrim, tapi peminum sering/harian sedikit lebih terbuka terhadap pengalaman baru.

#### 4. Ascore (Agreeableness)

- Titik tertinggi di CL1, turun di CL2-CL6.
- Pengguna alkohol cenderung punya skor Agreeableness lebih rendah, terutama yang makin rutin konsumsi.

#### 5. Cscore (Conscientiousness)

- Jelas terlihat tinggi di CL0 dan CL1. menurun di CL2-CL6.
- Artinya: Semakin sering konsumsi alkohol, cenderung semakin rendah skor kedisiplinan/tanggung jawabnya.


### **Kesimpulan**

- Neuroticism & Extraversion: Fluktuatif, tapi tidak ada pola kuat yang signifikan.
- Openness: Agak naik pada peminum berat.
- Agreeableness & Conscientiousness*: Jelas lebih rendah pada pengguna alkohol, terutama rutin (CL4 ke atas).

### **Distribusi dan hubungan variabel demografi terhadap status penggunaan zat Alkohol**
"""

import seaborn as sns
import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 3, figsize=(21, 6))

# Barplot Gender vs Alkohol
sns.countplot(x='Alcohol', hue='Gender', data=df, palette='Set2', ax=axes[0])
axes[0].set_title('Distribusi Gender terhadap Alkohol')
axes[0].tick_params(axis='x', rotation=0)

# Barplot Age vs Alkohol
sns.countplot(x='Alcohol', hue='Age', data=df, palette='Set2', ax=axes[1])
axes[1].set_title('Distribusi Umur terhadap Alkohol')
axes[1].tick_params(axis='x', rotation=0)

# Barplot Education vs Alkohol
sns.countplot(x='Alcohol', hue='Education', data=df, palette='Set2', ax=axes[2])
axes[2].set_title('Distribusi Pendidikan terhadap Alkohol')
axes[2].tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.show()

"""Berdasarkan visualisasi barplot demografi terhadap status penggunaan alcohol, dapat diketahui sebagai berikut

1. Distribusi Gender terhadap Alkohol

  Grafik ini menunjukkan bahwa baik pria maupun wanita paling banyak berada pada kategori konsumsi alkohol CL5 (tertinggi), disusul CL6. Pria cenderung sedikit lebih banyak pada kategori CL6, sedangkan wanita lebih dominan pada CL5. Ini mengindikasikan bahwa konsumsi alkohol tinggi terjadi pada kedua gender, dengan kecenderungan lebih tinggi pada wanita di kategori tertinggi.

2. Distribusi Umur terhadap Alkohol

  Kelompok umur 18–24 tahun adalah yang paling dominan dalam konsumsi alkohol tinggi (CL5 dan CL6), disusul kelompok 25–34 tahun. Semakin tua kelompok umur, konsumsi alkohol cenderung menurun. Ini menandakan bahwa konsumsi alkohol tinggi lebih umum pada usia muda.

3. Distribusi Pendidikan terhadap Alkohol

  Orang dengan pendidikan “University degree” paling banyak dalam kategori konsumsi alkohol tinggi (CL5), disusul oleh yang hanya memiliki “Some college/university, no degree.” Sebaliknya, mereka yang berhenti sekolah di usia muda cenderung lebih sedikit mengonsumsi alkohol. Artinya, semakin tinggi pendidikan, kecenderungan konsumsi alkohol juga meningkat.

### **Personality vs Drug Use**
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn.preprocessing import LabelEncoder # Import LabelEncoder

# list drug columns
drug_columns = [
    'Alcohol',
    'Amphetamines',
    'Amyl Nitrite',
    'Benzodiazepines',
    'Caffeine',
    'Cannabis',
    'Chlorpromazine',
    'Cocaine',
    'Crack',
    'Ecstasy',
    'Heroin',
    'Ketamine',
    'Legal Highs',
    'LSD',
    'Methadone',
    'Magic Mushrooms',
    'Nicotine',
    'Semer',
    'VSA'
]


# Gabungkan personality dan drug usage
personality_features = ['Nscore', 'Escore', 'Oscore', 'Ascore', 'Cscore', 'Impulsive', 'SS']
encoded_drug_use = df[drug_columns].apply(LabelEncoder().fit_transform)
corr_df = pd.concat([df[personality_features], encoded_drug_use], axis=1)

# Korelasi
plt.figure(figsize=(18, 10))
sns.heatmap(corr_df.corr().loc[personality_features, drug_columns], annot=True, fmt=".2f", cmap='coolwarm')
plt.title('Korelasi antara Kepribadian dan Penggunaan Zat')
plt.show()

"""Visualisasi Heatmap di atas menunjukkan hubungan (korelasi) antara tujuh dimensi kepribadian dan penggunaan berbagai jenis zat (obat-obatan atau narkoba).
1. Oscore (Openness to experience)
   Korelasi paling tinggi di antara semua dimensi kepribadian, terutama dengan LSD (0.37), Magic Mushrooms (0.37), dan Cannabis (0.41). Hal ini menunjukkan bahwa individu yang terbuka pada pengalaman baru cenderung lebih mungkin menggunakan zat-zat ini.

2. SS (Sensation Seeking)
   Korelasi positif kuat dengan berbagai zat, terutama Cannabis (0.46), LSD (0.41), dan Ecstasy (0.39). Artinya, individu yang mencari sensasi lebih tinggi lebih rentan menggunakan berbagai jenis zat.

3. Impulsive
   Juga memiliki korelasi cukup positif terhadap zat-zat seperti Cannabis (0.31), Crack (0.26), dan LSD (0.27), menunjukkan bahwa sifat impulsif bisa menjadi faktor risiko penggunaan zat.

4. Cscore (Conscientiousness) dan Ascore (Agreeableness)
   Cenderung berkorelasi negatif secara konsisten terhadap hampir semua zat. Artinya, orang yang teliti dan mudah bekerja sama cenderung lebih rendah risikonya dalam menggunakan zat.

5. Nscore (Neuroticism) dan Escore (Extraversion)
   Hubungannya lemah atau tidak konsisten terhadap sebagian besar zat, menunjukkan pengaruh yang lebih kecil atau bervariasi tergantung jenis zatnya.


**Kesimpulan:**
Sifat kepribadian seperti keterbukaan terhadap pengalaman baru, pencarian sensasi, dan impulsivitas memiliki hubungan yang paling kuat terhadap penggunaan zat. Sedangkan, sifat kehati-hatian dan keramahan menunjukkan efek protektif. Visualisasi ini penting untuk memahami faktor psikologis dalam pencegahan dan penanganan penyalahgunaan zat.

# **Data Preparation**

## **1. Mengubah Age Menjadi Format Numerik**

Kolom Age awalnya berisi data dalam bentuk rentang usia (misalnya "25-34") atau kategori berbentuk string. Karena model machine learning, khususnya regresi, membutuhkan data numerik untuk melakukan perhitungan, maka rentang tersebut dikonversi menjadi nilai tengah dari masing-masing rentang agar bisa direpresentasikan sebagai angka.

Alasan:
Model seperti regresi tidak bisa langsung memproses data dalam bentuk rentang kategori (string), karena tidak merepresentasikan hubungan numerik yang jelas. Dengan mengubah rentang usia menjadi angka tengahnya, kita mendapatkan estimasi usia yang lebih realistis dan bisa digunakan untuk analisis numerik terhadap target variabel.
"""

import numpy as np

def convert_age(age_str):
    if pd.isnull(age_str):  # jika kosong, return nan
        return np.nan
    if isinstance(age_str, (int, float)):
        return age_str
    if '-' in age_str:  # untuk tanda '-'
        try:
            parts = age_str.split('-')  # pisah menjadi ['25', '34']
            return (int(parts[0]) + int(parts[1])) // 2  # rata-rata 25+34 dibagi 2 = 29
        except:
             return np.nan # Handle potential errors in splitting or converting parts
    elif age_str.endswith('+'): # Handle cases like '65+'
        try:
            return int(age_str[:-1]) # Convert the number part before the '+'
        except:
            return np.nan # Handle cases where the part before '+' isn't a number
    else:
        try:
            return int(age_str)  # jika hanya angka, langsung konversi ke int
        except:
            return np.nan  # return nan

df['Age'] = df['Age'].apply(convert_age)

"""Fungsi convert_age digunakan untuk membersihkan data usia dalam bentuk string, seperti '25-34', '65+', atau '30', menjadi nilai numerik tunggal, seperti berikut:

- Jika kosong (NaN) → dikembalikan sebagai np.nan.

- Jika rentang usia seperti '25-34' → dihitung rata-ratanya (misal: 29).

- Jika format '65+' → diambil angkanya saja (misal: 65).

- Jika sudah angka biasa (misal '30') → langsung dikonversi ke integer.

- Jika gagal diproses → dikembalikan sebagai np.nan.

Fungsi ini diterapkan ke kolom 'Age' menggunakan df['Age'].apply(convert_age) untuk memastikan semua nilai usia dalam bentuk numerik.

## **2. Mapping Target ke Bentuk Numerik**


Target awal jenis obat berupa kategori teks, seperti berikut:
- CL0: Never (Tidak pernah menggunakan)
- CL1: Used over a decade ago (Pernah menggunakan lebih dari 10 tahun yang lalu)
- CL2: Used in last decade (Pernah menggunakan dalam 10 tahun terakhir)
- CL3: Used in last year (Pernah menggunakan dalam 1 tahun terakhir)
- CL4: Used in last month (Pernah menggunakan dalam 1 bulan terakhir)
- CL5: Used in last week (Pernah menggunakan dalam 1 minggu terakhir)
- CL6: Used in last day (Pernah menggunakan dalam 1 hari terakhir).

karena pemodelan regresi membutuhkan variabel numerik, maka kategori-kategori tersebut diubah menjadi angka ordinal yang mencerminkan tingkat frekuensi penggunaan.

Alasan:
Model regresi tidak dapat memproses data target dalam bentuk teks. Oleh karena itu, diperlukan konversi ke angka ordinal agar model bisa mengenali urutan tingkat frekuensi konsumsi, dari yang paling jarang (misalnya tidak pernah) hingga yang paling sering. Pendekatan ini membantu model memahami pola hubungan antara fitur-fitur input dengan tingkat konsumsi target secara lebih tepat.
"""

freq_map = {
    'CL0': 0,
    'CL1': 1,
    'CL2': 2,
    'CL3': 3,
    'CL4': 4,
    'CL5': 5,
    'CL6': 6
}

drug_columns = [
    'Alcohol',
    'Amphetamines',
    'Amyl Nitrite',
    'Benzodiazepines',
    'Caffeine',
    'Cannabis',
    'Chlorpromazine',
    'Cocaine',
    'Crack',
    'Ecstasy',
    'Heroin',
    'Ketamine',
    'Legal Highs',
    'LSD',
    'Methadone',
    'Magic Mushrooms',
    'Nicotine',
    'Semer',
    'VSA'
]

for drug in drug_columns:
    df[f'{drug}_freq'] = df[drug].map(freq_map)

"""## **3. Pemiilihan Fitur dan Target**

Fitur yang digunakan disesuaikan dengan rumusan masalah, yaitu terdiri dari:

- Fitur demografi: Age, Gender, Education, Country, Ethnicity

- Fitur psikologis: Nscore, Escore, Oscore, Ascore, Cscore, Impulsive, dan SS

Target yang diprediksi adalah frekuensi penggunaan untuk setiap jenis obat.

Alasan:
Pemilihan fitur dilakukan secara selektif untuk memastikan bahwa hanya variabel yang relevan dengan perilaku konsumsi obat yang digunakan. Fitur demografi dan psikologis dianggap memiliki pengaruh terhadap kebiasaan tersebut, sesuai dengan dasar teori dan rumusan masalah.
Selain itu, target juga harus dalam bentuk numerik agar dapat digunakan dalam model regresi. Hal ini memungkinkan model untuk belajar pola hubungan antara karakteristik individu dengan tingkat frekuensi penggunaan obat secara efektif.
"""

features = ['Age', 'Gender', 'Education', 'Country', 'Ethnicity',
            'Nscore', 'Escore', 'Oscore', 'Ascore', 'Cscore', 'Impulsive', 'SS']

target_1 = 'Alcohol_freq'
target_2 = 'Amphetamines_freq'
target_3 = 'Amyl Nitrite_freq'
target_4 = 'Benzodiazepines_freq'
target_5 = 'Caffeine_freq'
target_6 = 'Cannabis_freq'
target_7 = 'Chlorpromazine_freq'
target_8 = 'Cocaine_freq'
target_9 = 'Crack_freq'
target_10 = 'Ecstasy_freq'
target_11 = 'Heroin_freq'
target_12 = 'Ketamine_freq'
target_13 = 'Legal Highs_freq'
target_14 = 'LSD_freq'
target_15 = 'Methadone_freq'
target_16 = 'Magic Mushrooms_freq'
target_17 = 'Nicotine_freq'
target_18 = 'Semer_freq'
target_19 = 'VSA_freq'

"""## **4. Encoding Fitur Kategori**


Beberapa fitur seperti Gender, Education, Country, dan Ethnicity merupakan data kategorikal dalam bentuk string. Agar bisa digunakan dalam model machine learning, fitur-fitur ini perlu diubah ke format numerik menggunakan
OneHotEncoder. OneHotEncoder mengubah setiap kategori menjadi kolom biner (0 atau 1), sehingga tidak ada asumsi urutan di antara kategori tersebut. Misalnya, kategori Gender dengan nilai Male dan Female akan diubah menjadi dua kolom: Gender_Male dan Gender_Female.

Alasan:
Model machine learning, terutama yang berbasis numerik seperti regresi, tidak dapat memproses string secara langsung. Selain itu, jika kategori dikodekan sebagai angka biasa (seperti 1, 2, 3), model bisa keliru menganggap ada urutan atau jarak antar nilai. Dengan menggunakan OneHotEncoder:

- Tidak ada asumsi urutan antar kategori
- Menghindari bias model akibat interpretasi angka yang keliru
- Cocok untuk fitur kategorikal nominal
"""

import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

cat_features = ['Gender', 'Education', 'Country', 'Ethnicity']
features = ['Age', 'Gender', 'Education', 'Country', 'Ethnicity',
            'Nscore', 'Escore', 'Oscore', 'Ascore', 'Cscore', 'Impulsive', 'SS']

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore'), cat_features)
    ],
    remainder='passthrough'
)

# Fit and transform the data using the selected features
X_encoded = preprocessor.fit_transform(df[features])

# Use the column names that the transformer was fitted on (cat_features)
ohe_cols = preprocessor.named_transformers_['cat'].get_feature_names_out(cat_features)

# Gabung semua nama kolom: kolom hasil OHE + numerik yang "passthrough"
passthrough_cols = [col for col in features if col not in cat_features]
all_cols = list(ohe_cols) + passthrough_cols

# Dataframe hasil transformasi
X_encoded_df = pd.DataFrame(X_encoded, columns=all_cols)
X_encoded_df.head()

"""Kode ini melakukan encoding fitur kategorikal (Gender, Education, Country, Ethnicity) menjadi vektor one-hot, dan menggabungkannya dengan fitur numerik lain (seperti Age, skor kepribadian, dll) menjadi satu DataFrame numerik.

## **5. Split Data Train-Test**

Data dibagi menjadi dua bagian:

- 80% untuk data latih (training set)
- 20% untuk data uji (test set)

Pembagian ini dilakukan untuk setiap target prediksi yang digunakan dalam pemodelan., dalam penelitian ini adalah setiap jenis obat.

Alasan:
Tujuan dari membagi data adalah agar model bisa dilatih pada satu bagian data latih (train set), lalu diuji performanya pada data yang belum pernah dilihat sebelumnya (test set). Manfaatnya adalah:

- Menghindari overfitting
- Memastikan model bisa beradaptasi dengan data baru yang belum pernah muncul sebelumnya
"""

from sklearn.model_selection import train_test_split

X = df[features]

y_1 = df[target_1]
y_2 = df[target_2]
y_3 = df[target_3]
y_4 = df[target_4]
y_5 = df[target_5]
y_6 = df[target_6]
y_7 = df[target_7]
y_8 = df[target_8]
y_9 = df[target_9]
y_10 = df[target_10]
y_11 = df[target_11]
y_12 = df[target_12]
y_13 = df[target_13]
y_14 = df[target_14]
y_15 = df[target_15]
y_16 = df[target_16]
y_17 = df[target_17]
y_18 = df[target_18]
y_19 = df[target_19]

X_train, X_test, y_train_1, y_test_1 = train_test_split(X, y_1, test_size=0.2, random_state=42)
X_train, X_test, y_train_2, y_test_2 = train_test_split(X, y_2, test_size=0.2, random_state=42)
X_train, X_test, y_train_3, y_test_3 = train_test_split(X, y_3, test_size=0.2, random_state=42)
X_train, X_test, y_train_4, y_test_4 = train_test_split(X, y_4, test_size=0.2, random_state=42)
X_train, X_test, y_train_5, y_test_5 = train_test_split(X, y_5, test_size=0.2, random_state=42)
X_train, X_test, y_train_6, y_test_6 = train_test_split(X, y_6, test_size=0.2, random_state=42)
X_train, X_test, y_train_7, y_test_7 = train_test_split(X, y_7, test_size=0.2, random_state=42)
X_train, X_test, y_train_8, y_test_8 = train_test_split(X, y_8, test_size=0.2, random_state=42)
X_train, X_test, y_train_9, y_test_9 = train_test_split(X, y_9, test_size=0.2, random_state=42)
X_train, X_test, y_train_10, y_test_10 = train_test_split(X, y_10, test_size=0.2, random_state=42)
X_train, X_test, y_train_11, y_test_11 = train_test_split(X, y_11, test_size=0.2, random_state=42)
X_train, X_test, y_train_12, y_test_12 = train_test_split(X, y_12, test_size=0.2, random_state=42)
X_train, X_test, y_train_13, y_test_13 = train_test_split(X, y_13, test_size=0.2, random_state=42)
X_train, X_test, y_train_14, y_test_14 = train_test_split(X, y_14, test_size=0.2, random_state=42)
X_train, X_test, y_train_15, y_test_15 = train_test_split(X, y_15, test_size=0.2, random_state=42)
X_train, X_test, y_train_16, y_test_16 = train_test_split(X, y_16, test_size=0.2, random_state=42)
X_train, X_test, y_train_17, y_test_17 = train_test_split(X, y_17, test_size=0.2, random_state=42)
X_train, X_test, y_train_18, y_test_18 = train_test_split(X, y_18, test_size=0.2, random_state=42)
X_train, X_test, y_train_19, y_test_19 = train_test_split(X, y_19, test_size=0.2, random_state=42)

"""## **6. Transform Data dengan Preprocessing Pipeline**

Digunakan preprocessing pipeline untuk mengatur proses transformasi data, terutama pada fitur kategorikal.

- Fitur kategorikal seperti Gender, Education, Country, dan Ethnicity di-encode menggunakan OneHotEncoder.
- Fitur numerik langsung digunakan karena data sudah dinormalisasi sejak awal.

Alasan:
Menggunakan pipeline mempunyai banyak kelebihan:

- Mengotomatisasi proses encoding pada data train dan test, tanpa perlu transformasi manual.
- Menjaga konsistensi: transformasi yang dilakukan pada data latih akan secara otomatis diterapkan juga ke data uji, sehingga tidak terjadi mismatch.
- Memudahkan proses modeling, baik saat pelatihan maupun saat prediksi di data baru.
- Fitur numerik tetap utuh, karena pipeline bisa diatur hanya memproses kolom yang dibutuhkan saja, tanpa mengubah yang sudah siap pakai.
"""

X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

print(f"Dimensi data train sebelum preprocessing: {X_train.shape}")
print(f"Dimensi data train setelah preprocessing: {X_train_processed.shape}")

"""Setelah dilakukan one-hot encoding terhadap fitur kategorikal, jumlah fitur meningkat dari 12 menjadi 33. Hal ini terjadi karena setiap kategori dipecah menjadi beberapa kolom biner (dummy variables), sementara fitur numerik tetap dipertahankan.

# **Modeling**

## **Linear Regression**

Linear Regression adalah model statistik sederhana dan mudah diinterpretasikan. Model ini mengasumsikan adanya hubungan linear antara fitur (X) dan target (y).

Kelebihan:

- Mudah diinterpretasikan: kita bisa tahu seberapa besar pengaruh tiap fitur ke target.
- Cepat dilatih, bahkan pada dataset besar.
- Cocok untuk baseline model karena sederhana.

Kekurangan:

- Tidak cocok untuk hubungan non-linear.
- Sangat sensitif terhadap outlier.
- Asumsi multikolinearitas dan homoskedastisitas bisa sulit dipenuhi.


### **Tahapan dan Parameter Pemodelan**

1. Inisialisasi Model:

   ```python
   model = LinearRegression()
   ```

   Tidak ada hyperparameter khusus pada LinearRegression dari `sklearn`.

2. Training Model:
   Model dilatih untuk masing-masing dari 19 jenis obat (target variabel: y1 sampai y19) menggunakan data yang sudah diproses (X_train_processed, y_train_i).

3. Evaluasi:
   Model dievaluasi dengan metrik:

   - MAE (Mean Absolute Error)
   - MSE (Mean Squared Error)
   - R² (Koefisien Determinasi)

   Semua metrik dihitung menggunakan test set (X_test_processed, y_test_i).

4. Koefisien:
   Koefisien dari setiap fitur disimpan dalam DataFrame, untuk dianalisis pengaruhnya terhadap setiap jenis obat.
"""

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import pandas as pd
import numpy as np

mae_lr = []
mse_lr = []
r2_lr = []
coefs_lr = []

for i in range(1, 20):
    y_train_i = globals()[f"y_train_{i}"]
    y_test_i = globals()[f"y_test_{i}"]

    model = LinearRegression()
    # Fit the model using the processed training data
    model.fit(X_train_processed, y_train_i)

    # Predict on the processes test data to evaluate test performance
    y_pred = model.predict(X_test_processed)

    # Evaluate metrics on the test set
    mae_lr.append(mean_absolute_error(y_test_i, y_pred))
    mse_lr.append(mean_squared_error(y_test_i, y_pred))
    r2_lr.append(r2_score(y_test_i, y_pred))

    # Store coefficients
    coefs_lr.append(model.coef_)

# Koefisien jadi DataFrame pakai nama kolom yang sudah disiapkan
coef_df = pd.DataFrame(coefs_lr, columns=all_cols)
coef_df["Drug"] = drug_columns
coef_df["R²"] = r2_lr
coef_df = coef_df[["Drug", "R²"] + all_cols]

print("Koefisien Linear Regression:")
print(coef_df.round(4))

"""Setiap model regresi dilakukan untuk masing-masing dari 19 jenis zat, dan koefisien menunjukkan arah serta kekuatan pengaruh masing-masing variabel terhadap frekuensi penggunaan zat.

#### **Variabel Psikologis Kepribadian**

**1. Neuroticism (Nscore)**

Cenderung positif pada zat-zat seperti Benzodiazepines (0.3878), Heroin (0.0820), dan Nicotine (0.0970), menunjukkan bahwa individu dengan tingkat neurotisisme tinggi lebih rentan menggunakan zat sebagai pelarian dari stres atau tekanan emosional.

**2. Extraversion (Escore)**

Bervariasi, tapi terlihat positif pada Cocaine (0.1117), Ecstasy (0.1375), dan Nicotine (0.0302), menunjukkan bahwa individu ekstrovert yang suka stimulasi sosial lebih cenderung menggunakan zat yang berkaitan dengan euforia atau aktivitas sosial.

**3. Openness to Experience (Oscore)**

Sangat positif pada Cannabis (0.4616), LSD (0.2596), dan Magic Mushrooms (0.2282), memperkuat hubungan antara keterbukaan terhadap pengalaman baru dengan eksplorasi penggunaan zat-zat psikedelik atau alternatif.

**4. Agreeableness (Ascore)**

Negatif untuk banyak zat seperti Cocaine (-0.1143), Benzodiazepines (-0.0741), dan Heroin (-0.0686), menandakan bahwa orang yang cenderung kooperatif dan penuh empati kurang tertarik terhadap penggunaan zat-zat tersebut.

**5. Conscientiousness (Cscore)**

Konsisten negatif, misalnya pada Cannabis (-0.2101), Ecstasy (-0.2027), dan Nicotine (-0.2156). Ini menunjukkan bahwa orang yang terorganisir dan berhati-hati cenderung menghindari perilaku berisiko seperti penggunaan zat.


#### **Impulsivity & Sensation Seeking**

**1. Impulsivity**

Positif dan cukup kuat pada zat-zat seperti Amphetamines (0.1611), Cannabis (0.0794), dan Nicotine (0.1935), menunjukkan bahwa individu yang lebih impulsif cenderung lebih sering menggunakan zat karena dorongan sesaat atau kontrol diri yang rendah.

**2. Sensation Seeking (SS)**
Sangat tinggi pada Cannabis (0
.3430), Cocaine (0.3027), Legal Highs (0.3074), dan Ecstasy (0.2574), menunjukkan bahwa mereka yang haus pengalaman intens dan baru lebih rentan terhadap penggunaan zat dengan efek kuat atau menantang.


#### **Variabel Demografis**

**1. Jenis Kelamin**

- Pria (Gender\_Male): Positif untuk hampir semua zat, misalnya Cannabis (0.2811), Legal Highs (0.3034), dan Amphetamines (0.1931)
- Wanita (Gender\_Female): Negatif (karena dummy variabel), artinya pria lebih cenderung menggunakan zat daripada wanita

**2. Usia (Age)**

Umumnya negatif pada zat-zat seperti Cannabis (-0.0374), Ecstasy (-0.0312), dan Legal Highs (-0.0309), mengindikasikan bahwa kelompok usia muda memiliki kecenderungan lebih tinggi untuk mengonsumsi zat tersebut.

**3. Pendidikan (Education)**

- **Left school before 16 years**: positif besar pada Cannabis (0.9481) dan Nicotine (1.0041), memperlihatkan bahwa pendidikan rendah merupakan faktor risiko kuat
- **Masters degree**: efek cenderung negatif, seperti Cannabis (-0.5020) dan Nicotine (-0.5756), menunjukkan bahwa pendidikan tinggi dapat menjadi faktor pelindung dari penggunaan zat

**4. Etnisitas (Ethnicity)**

- **Ethnicity\_Other** positif besar pada zat seperti Cocaine (0.5176) dan Ecstasy (0.6960), artinya kelompok etnis tertentu mungkin memiliki pola penggunaan yang lebih tinggi, meskipun bisa juga dipengaruhi faktor sosial dan budaya
- **Ethnicity\_White** juga memiliki beberapa pengaruh positif, seperti pada Alcohol (0.3943), tapi umumnya lebih kecil dibandingkan kelompok *Other*


### **Kesimpulan**

- Openness, sensation seeking, dan impulsivity jadi prediktor psikologis yang paling kuat untuk berbagai jenis zat, terutama yang bersifat eksploratif dan stimulatif
- Neuroticism berhubungan dengan zat yang dipakai sebagai coping mechanism, seperti benzodiazepine dan heroin
- Conscientiousness dan agreeableness tampak sebagai faktor pelindung, karena punya arah negatif hampir di semua jenis zat
- Dari sisi demografi, pria, usia muda, dan pendidikan rendah adalah kelompok yang punya risiko lebih tinggi terhadap penggunaan zat

## **Random Forest Regressor**

Random Forest adalah ensemble model berbasis decision tree yang membentuk banyak pohon (trees) dan menggabungkan hasilnya untuk prediksi akhir.

Kelebihan:

- Menangani hubungan non-linear dan interaksi antar fitur secara otomatis.
- Tidak sensitif terhadap multikolinearitas.
- Tidak memerlukan scaling atau normalisasi data.
- Dapat memberikan feature importance → membantu memahami pengaruh tiap variabel.

Kekurangan:

- Interpretasi model lebih sulit dibanding Linear Regression.
- Bisa overfit jika jumlah pohon terlalu banyak atau kedalaman pohon terlalu dalam.
- Waktu komputasi lebih tinggi dibanding model linear.


### **Tahapan Pemodelan dan Parameter**

1. Inisialisasi Model:

   ```python
   rf_model = RandomForestRegressor(random_state=42)
   ```

   Default parameter digunakan (bisa dilakukan tuning di tahap lanjutan).

2. Training Model:
   Model dilatih untuk masing-masing dari 19 target (obat) menggunakan data training hasil preprocessing.

3. Evaluasi:
   Evaluasi dilakukan pada data test menggunakan:

   - MAE (Mean Absolute Error)
   - MSE (Mean Squared Error)
   - R² Score

   Semua nilai dimasukkan ke dalam list `mae_rf`, `mse_rf`, dan `r2_rf`.

4. Feature Importance:
   Untuk setiap model, dihitung importance masing-masing fitur. Importance ini menggambarkan kontribusi relatif fitur dalam prediksi.
"""

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Initialize lists for metrics and feature importances
mae_rf = []
mse_rf = []
r2_rf = []
importances_rf = []

for i in range(1, 20):
    # Get the training and testing target variables for the current drug
    y_train_i = globals()[f"y_train_{i}"]
    y_test_i = globals()[f"y_test_{i}"]

    # Initialize the Random Forest Regressor model
    rf_model = RandomForestRegressor(random_state=42)

    # Fit the model using the processed training data and the corresponding training target
    rf_model.fit(X_train_processed, y_train_i)

    # Predict on the PROCESSED TEST data to evaluate performance on unseen data
    y_pred_rf = rf_model.predict(X_test_processed)

    # Evaluate metrics using the actual test target and the predictions on the test data
    mae_rf.append(mean_absolute_error(y_test_i, y_pred_rf))
    mse_rf.append(mean_squared_error(y_test_i, y_pred_rf))
    r2_rf.append(r2_score(y_test_i, y_pred_rf))

    # Store feature importances from the fitted model
    importances_rf.append(rf_model.feature_importances_)

# DataFrame feature importances Random Forest
featimp_df = pd.DataFrame(importances_rf, columns=all_cols)
featimp_df["Drug"] = drug_columns
featimp_df["R²"] = r2_rf
featimp_df = featimp_df[["Drug", "R²"] + all_cols]

print("Feature Importances Random Forest:")
print(featimp_df.round(4))

"""Model Random Forest Regressor digunakan untuk memprediksi tingkat penggunaan 19 jenis zat psikoaktif berdasarkan fitur demografis dan psikologis. Kepentingan masing-masing fitur (feature importances) dilihat dari besarnya kontribusi terhadap model prediksi.

#### **1. Faktor Psikologis Kepribadian**

Beberapa traits berperan penting dalam memprediksi perilaku konsumsi, di antaranya:

- Neuroticism (Nscore): Sangat tinggi untuk Benzodiazepines (0.1408), Caffeine (1283), dan Chlorpromazine (1274), mengindikasikan individu dengan neuroticism tinggi cenderung menggunakan zat yang bersifat penenang.

- Extraversion (Escore) & Openness (Oscore): Punya kontribusi besar untuk Cannabis, Ecstasy, dan LSD, zat-zat yang biasanya berhubungan dengan eksplorasi dan sosial.

- Agreeableness (Ascore) & Conscientiousness (Cscore): Umumnya menurunkan kemungkinan penggunaan, tapi nilainya tetap signifikan dalam memodelkan variasi perilaku.


#### **2. Sensation Seeking & Impulsiveness**

- Sensation Seeking (SS): Tinggi untuk Ecstasy (0.1696), cocaine (0.1599), Cannabis (0.1222), Nicotine (0.1199), dan Lagel Highs (0.1170) memperkuat temuan bahwa individu pencari sensasi cenderung mengeksplorasi berbagai jenis zat.

- Impulsiveness: Penting untuk zat-zat seperti Amphetamines , Crack, dan LSD, di mana keputusan impulsif bisa jadi pendorong utama konsumsi.


#### **3. Variabel Demografis**

- Gender: Tidak terlalu berpengaruh secara signifikan untuk sebagian besar prediksi, namun tetap punya nilai kontribusi kecil yang merata.

- Education: Beberapa level pendidikan memberi kontribusi kecil, terutama untuk prediksi zat-zat seperti Ecstasy, LSD, dan Legal Highs.

- Ethnicity: Pengaruhnya rendah, namun Ethnicity\_Other cukup tinggi untuk Semer (0.1060), menandakan adanya pola konsumsi unik pada kelompok etnis minoritas.

- Age: Termasuk salah satu fitur penting untuk beberapa zat, terutama Legal Highs (0.1544) dan Ecstasy (0.1082), menunjukkan bahwa umur mempengaruhi kecenderungan konsumsi.


#### **Kesimpulan**

Model Random Forest Regressor berhasil mengidentifikasi fitur-fitur yang relevan dalam memprediksi konsumsi zat tertentu, terutama:

* Cannabis, Ecstasy, LSD, Legal Highs, dan Amphetamines: diprediksi cukup baik.
* Umur, traits psikologis (terutama Openness to Experience (Oscore), Neuroticism (Nscore), Sensation Seeking (SS)), dan pendidikan: jadi prediktor penting.

# **Evaluasi**

### 1. **Metrik Evaluasi yang Digunakan**

Untuk mengukur performa dari model regresi yang dibangun (Linear Regression dan Random Forest), digunakan tiga metrik evaluasi utama, yaitu:

- **Mean Absolute Error (MAE):**
  
  $$
  MAE = \frac{1}{n} \sum_{i=1}^n |y_i - \hat{y}_i|
  $$

  Metrik ini mengukur rata-rata selisih absolut antara nilai aktual dan nilai prediksi. MAE mudah dipahami karena menggunakan satuan yang sama dengan target, dan tidak terlalu sensitif terhadap outlier.

- **Mean Squared Error (MSE):**
  
  $$
  MSE = \frac{1}{n} \sum_{i=1}^n (y_i - \hat{y}_i)^2
  $$

  MSE mengkuadratkan selisih prediksi agar penalti terhadap kesalahan besar menjadi lebih tinggi. Metrik ini lebih sensitif terhadap outlier dibanding MAE.

- **R-squared (R²):**
  
  $$
  R^2 = 1 - \frac{\sum_{i=1}^n (y_i - \hat{y}_i)^2}{\sum_{i=1}^n (y_i - \bar{y})^2}
  $$

  Metrik ini menunjukkan seberapa besar proporsi variasi dalam data target yang bisa dijelaskan oleh model. Nilai R² berkisar antara minus tak hingga sampai 1, dengan nilai mendekati 1 menandakan model yang lebih baik.


### 2. **Kesesuaian Metrik dengan Problem Statement**

Karena tujuan dari proyek ini adalah memprediksi tingkat penggunaan obat berdasarkan data demografi dan kepribadian, maka:

- MAE & MSE cocok digunakan karena kita ingin tahu seberapa besar prediksi kita meleset dari nilai sebenarnya.
- R² penting untuk melihat apakah model benar-benar menangkap pola dari data. Ini membantu mengevaluasi apakah model punya daya prediksi yang kuat.


### 3. **Penjelasan Hasil Proyek Berdasarkan Metrik**

Evaluasi dilakukan untuk **setiap target obat (y₁ sampai y₁₉)** dan hasilnya dikompilasi dalam bentuk DataFrame (`eval_df`) yang menyajikan nilai MAE, MSE, dan R² untuk setiap model:

```python
print(eval_df)
```
"""

import pandas as pd

# list simpan hasil evaluasi semua target
results = []

for i in range(1, 20):
    mae_lr_i = mae_lr[i-1]
    mse_lr_i = mse_lr[i-1]
    r2_lr_i = r2_lr[i-1]

    mae_rf_i = mae_rf[i-1]
    mse_rf_i = mse_rf[i-1]
    r2_rf_i = r2_rf[i-1]

    results.append({
        "Target": f"y_{i}",
        "Drug": drug_columns[i-1],
        "Model": "Linear Regression",
        "MAE": mae_lr_i,
        "MSE": mse_lr_i,
        "R²": r2_lr_i
    })
    results.append({
        "Target": f"y_{i}",
        "Drug": drug_columns[i-1],
        "Model": "Random Forest",
        "MAE": mae_rf_i,
        "MSE": mse_rf_i,
        "R²": r2_rf_i
    })

# DataFrame
eval_df = pd.DataFrame(results)
print(eval_df)

"""### **Berikut ini adalah ringkasan informasi evaluasi model berdasarkan hasil di atas:**

### **Model Linear Regression**

Model ini menunjukkan performa paling baik dibandingkan Random Forest dalam mayoritas prediksi, terutama ditandai dengan nilai R² yang konsisten lebih tinggi.

Hasil terbaik ditunjukkan pada prediksi:

- Cannabis: R² = 0.4886 → hampir 49% variasi frekuensi penggunaan bisa dijelaskan model.
- Legal Highs: R² = 0.3905
- Magic Mushrooms: R² = 0.3086
- LSD: R² = 0.3016
- Ecstasy: R² = 0.2391
- Amphetamines: R² = 0.2211
- Methadone: R² = 0.2161
- Benzodiazepines: R² = 0.2048

Hasil ini menunjukkan bahwa Linear Regression mampu menangkap pola konsumsi pada zat yang lebih umum digunakan.

Namun, model ini kurang efektif untuk beberapa zat, seperti:

- Semer: R² = -0.0294
- Chlorpromazine: R² = 0.0052
- Caffeine: R² = 0.0290

Hal ini mengindikasikan bahwa model hampir tidak mampu menjelaskan variasi data untuk zat-zat tersebut.


### **Model Random Forest Regressor**

Performa cenderung lebih rendah dibandingkan Linear Regression pada sebagian besar target.


R² tertinggi tetap pada:

- Cannabis: R² = 0.4596, namun masih lebih rendah dibandingkan Linear Regression.
- Legal Highs: R² = 0.3476
- Magic Mushrooms: R² = 0.2799
- LSD: R² = 0.2970
- Ecstasy: R² = 0.2025

Namun, sering menghasilkan R² negatif, misalnya pada:

- Semer: R² = -0.7836 → terburuk, menunjukkan model benar-benar gagal mempelajari pola dari data.
- Alcohol: R² = -0.0866
- Caffeine: R² = -0.0569
- Chlorpromazine: R² = -0.0850
- Crack: R² = -0.0472
- VSA: R² = -0.0160

Model Random Forest kemungkinan mengalami overfitting atau tidak mampu menangkap pola konsisten.

### **Kesimpulan Evaluasi**

* Linear Regression lebih unggul dalam memodelkan pola konsumsi sebagian besar zat, khususnya yang konsumsinya lebih umum (seperti Cannabis, Ecstasy, Legal Highs).
* Random Forest tidak memberikan peningkatan performa berarti, bahkan cenderung lebih buruk, terutama pada zat dengan distribusi langka atau outlier.
* Nilai MAE dan MSE di kedua model umumnya berada di kisaran menengah, artinya masih ada potensi peningkatan akurasi prediksi, misalnya dengan tuning parameter atau penggunaan model lain seperti XGBoost, SVR, atau ensemble methods.
* Model juga dapat ditingkatkan dengan penyeimbangan data, terutama untuk zat yang kurang umum digunakan.

# **Comparison & Model Selection**

### **Perbandingan Model (Model Comparison)**

Berdasarkan hasil evaluasi terhadap 19 jenis zat psikoaktif dengan dua model regresi (Linear Regression dan Random Forest Regressor), dapat disimpulkan bahwa:

1. Linear Regression menunjukkan performa yang lebih stabil dan unggul dalam banyak kasus, khususnya pada zat-zat yang memiliki distribusi penggunaan yang lebih umum. Ini tercermin dari nilai R² yang konsisten lebih tinggi di hampir seluruh prediksi.

2. Random Forest Regressor seringkali memberikan performa lebih rendah, bahkan negatif pada beberapa target. Hal ini menandakan bahwa model ini:

   - Tidak mampu menggeneralisasi dengan baik,
   - Kemungkinan overfitting terhadap data latih,
   - Kurang optimal pada data dengan distribusi tidak seimbang.

3. Dari segi MAE dan MSE, Linear Regression juga relatif lebih baik untuk sebagian besar zat. Random Forest memang memiliki beberapa MAE yang sedikit lebih rendah, tapi diiringi dengan R² yang buruk, sehingga tidak cukup representatif sebagai model yang baik.

### **Pemilihan Model Terbaik (Model Selection)**

Berdasarkan perbandingan performa, Linear Regression dipilih sebagai model terbaik dalam analisis ini, dengan alasan berikut:

* R² tertinggi secara konsisten, khususnya pada target utama seperti Cannabis (0.4886), Legal Highs (0.3905), dan Magic Mushrooms (0.3086).
* Lebih stabil dan tidak menunjukkan R² negatif ekstrem seperti yang terjadi pada Random Forest.
* Interpretasi model lebih mudah, cocok dengan tujuan analisis yang ingin memahami hubungan antar variabel kepribadian/demografi terhadap frekuensi penggunaan zat.

# **Hyperparameter Tuning**

**Proses Improvement dengan Ridge Regression (Hyperparameter Tuning)**

Untuk mengatasi kelemahan Linear Regression, khususnya masalah overfitting dan multikolinearitas, dilakukan improvement dengan menggunakan Ridge Regression. Ridge Regression adalah varian Linear Regression yang menambahkan regularisasi L2 pada fungsi loss, yang membantu mengontrol kompleksitas model dengan menekan bobot koefisien agar tidak terlalu besar.

**Langkah-langkah improvement yang dilakukan:**

- Pencarian Nilai Optimal Hyperparameter (alpha)
  - Dilakukan tuning hyperparameter alpha, yang mengontrol kekuatan regularisasi.
  - Nilai alpha memengaruhi kompleksitas model:
    - Alpha kecil → model lebih fleksibel, risiko overfitting.
    - Alpha besar → model lebih sederhana, risiko underfitting.
  - Pencarian nilai optimal dilakukan dengan GridSearchCV, yang menguji kombinasi nilai alpha dari alpha_list = [0.01, 0.1, 1, 10, 100].

- Menggunakan Cross-Validation dalam Grid Search

  - GridSearchCV menggunakan cross-validation (cv=5) untuk memastikan model tidak hanya fit terhadap satu subset data.
  - Cross-validation mengurangi risiko overfitting saat memilih hyperparameter, karena mengevaluasi performa rata-rata dari beberapa fold data.

- Iterasi untuk Tiap Target Zat (Multi-Target Regression)

  - Model di-loop sebanyak 19 kali, masing-masing untuk satu target (zat psikoaktif berbeda).
  - Setiap iterasi melakukan tuning dan fitting model yang independen.
  - Hal ini memungkinkan model menangkap karakteristik unik dari masing-masing zat, karena efek prediktor bisa berbeda-beda.
"""

from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import pandas as pd
import numpy as np

mae_ridge = []
mse_ridge = []
r2_ridge = []
best_alphas = []
coefs_ridge = []

# List alpha yang akan dicoba (nilai regularisasi)
alpha_list = [0.01, 0.1, 1, 10, 100]

for i in range(1, 20):
    y_train_i = globals()[f"y_train_{i}"]
    y_test_i = globals()[f"y_test_{i}"]

    ridge = Ridge()
    # GridSearch untuk cari alpha terbaik
    param_grid = {'alpha': alpha_list}
    grid = GridSearchCV(ridge, param_grid, cv=5)
    grid.fit(X_train_processed, y_train_i)

    # Model dengan alpha terbaik
    best_model = grid.best_estimator_

    # Predict test data
    y_pred = best_model.predict(X_test_processed)

    # Evaluasi
    mae_ridge.append(mean_absolute_error(y_test_i, y_pred))
    mse_ridge.append(mean_squared_error(y_test_i, y_pred))
    r2_ridge.append(r2_score(y_test_i, y_pred))
    best_alphas.append(grid.best_params_['alpha'])
    coefs_ridge.append(best_model.coef_)

# Dataframe koefisien
coef_ridge_df = pd.DataFrame(coefs_ridge, columns=all_cols)
coef_ridge_df["Drug"] = drug_columns
coef_ridge_df["Best Alpha"] = best_alphas
coef_ridge_df["R²"] = r2_ridge
coef_ridge_df = coef_ridge_df[["Drug", "Best Alpha", "R²"] + all_cols]

print("Koefisien Ridge Regression dengan Hyperparameter Tuning:")
print(coef_ridge_df.round(4))

"""Hasil untuk hyperparameter tuning, sebagai berikut:
- Nilai R² tertinggi diperoleh pada prediksi Cannabis dengan R² sebesar 0.4905 dan alpha 10.
- Beberapa zat lain yang juga menunjukkan R² cukup tinggi adalah:

  - Magic Mushrooms (R² = 0.3137, alpha = 100)
  - LSD (R² = 0.3080, alpha = 10)
  - Legal Highs (R² = 0.3882, alpha = 100)
  - Ecstasy (R² = 0.2510, alpha = 100)

Namun, untuk sebagian besar zat lain, nilai R² tergolong rendah (di bawah 0.25), bahkan mendekati nol. Sebagai contoh:

- Alcohol (R² = 0.0412),
- Caffeine (R² = 0.0175),
- Chlorpromazine (R² = 0.0152),
- Semer (R² = -0.0178).

Catatan:
- Model Ridge dapat menurunkan overfitting dengan menambahkan penalti terhadap besar koefisien, sehingga dapat mengurangi varians walau dengan sedikit penurunan R².
- Efek dari variabel Openness, Sensation Seeking, dan Impulsiveness cenderung dominan dan konsisten berkontribusi positif terhadap prediksi penggunaan beberapa jenis zat.

#### **Performa Model**:

Rendahnya nilai R² pada sebagian besar zat menunjukkan bahwa fitur-fitur kepribadian dan demografis tidak cukup kuat dalam menjelaskan variasi perilaku konsumsi zat tersebut, kemungkinan karena pengaruh kuat dari faktor eksternal lain seperti budaya, lingkungan sosial, atau ketersediaan zat.

Meskipun demikian, performa cukup tinggi pada zat seperti Cannabis, Magic Mushrooms, dan LSD menunjukkan bahwa konsumsi zat-zat tersebut memiliki keterkaitan yang lebih konsisten dengan karakteristik psikologis individu.

# **Kesimpulan**

Berdasarkan hasil analisis yang dilakukan, penelitian ini berusaha menjawab dua rumusan masalah utama, yaitu:
1. bagaimana hubungan antara tingkat impulsivitas dan sensation seeking dengan frekuensi konsumsi zat psikoaktif
2. bagaimana model prediktif dapat digunakan untuk memprediksi frekuensi konsumsi zat berdasarkan karakteristik psikologis (big five personality traits) dan demografis.

Hasil analisis menunjukkan bahwa terdapat kecenderungan positif antara impulsiveness dan sensation seeking dengan frekuensi konsumsi berbagai jenis zat psikoaktif. Artinya, semakin tinggi tingkat impulsivitas dan pencarian sensasi seseorang, semakin tinggi pula kecenderungan mereka untuk lebih sering mengonsumsi zat. Selain itu, beberapa dimensi dari Big Five Personality Traits, seperti Neuroticism (N) dan Openness (O), juga menunjukkan kontribusi yang berarti dalam model prediktif, tergantung pada jenis zat yang dianalisis. Misalnya, individu dengan skor tinggi pada openness atau neuroticism cenderung memiliki frekuensi konsumsi zat tertentu yang lebih tinggi.

Akan tetapi, ketika dibangun model prediksi menggunakan Linear Regression dan dibandingkan dengan Random Forest Regressor, diperoleh bahwa Linear Regression memberikan hasil yang lebih baik secara umum. Selanjutnya, model ini ditingkatkan performanya dengan menggunakan Ridge Regression dan dilakukan tuning terhadap hyperparameter alpha untuk mendapatkan hasil terbaik. Akan tetapi, nilai R² tertinggi yang diperoleh tetap hanya sekitar 0.49 (Cannabis), sementara sebagian besar zat lainnya memiliki R² yang rendah, bahkan mendekati nol.

Performa model yang cenderung rendah ini bukan semata-mata disebabkan oleh kelemahan model itu sendiri, melainkan juga mencerminkan bahwa fitur-fitur yang tersedia, yaitu skor kepribadian (Big Five, sensation seeking, impulsiveness) dan variabel demografis (usia, jenis kelamin, pendidikan, dan etnis) kemungkinan tidak cukup kuat untuk menjelaskan variasi perilaku penggunaan zat secara signifikan.

Beberapa hal yang dapat menjelaskan kondisi ini:
1. Karakteristik psikologis bersifat umum, bukan spesifik terhadap penggunaan zat

   Meskipun Big Five dan konstruk lain seperti impulsivitas memiliki hubungan dengan perilaku adiktif, namun hubungan tersebut bersifat umum dan tidak spesifik terhadap zat tertentu, sehingga daya prediksinya secara frekuensi cenderung lemah.

2. Faktor eksternal yang tidak terukur dalam data

   Banyak faktor penting lain yang berperan dalam konsumsi zat seperti tekanan lingkungan, pengaruh sosial, stres, trauma masa lalu, atau kondisi kesehatan mental yang tidak terekam dalam dataset ini, sehingga model tidak mampu menangkapnya.

3. Distribusi target yang tidak merata dan noise yang tinggi

   Beberapa zat memiliki distribusi yang sangat skewed (mayoritas responden tidak mengonsumsi), sehingga mempersulit model dalam mengenali pola yang bermakna, apalagi jika tidak cukup data dari pengguna aktif.

3. Hasil tuning Ridge Regression sudah optimal, namun tetap tidak signifikan peningkatannya, menandakan bahwa batasan utama bukan dari teknik modelling, melainkan dari kapasitas informasi yang bisa disediakan oleh fitur yang digunakan.

Dengan kata lain, meskipun model sudah dikembangkan secara sistematis dan dilakukan tuning dengan benar, informasi yang tersedia dalam fitur-fitur yang digunakan belum cukup kuat untuk membangun model prediktif yang presisi terhadap frekuensi konsumsi zat.

# **Saran**

Berdasarkan keterbatasan dan hasil penelitian ini, beberapa saran untuk penelitian selanjutnya adalah sebagai berikut:

1. Penambahan Variabel yang Lebih Komprehensif

   Untuk meningkatkan akurasi model prediksi, disarankan memasukkan variabel tambahan yang berkaitan dengan faktor lingkungan sosial, dukungan keluarga, kondisi psikologis yang lebih spesifik (seperti stres, trauma, gangguan mental), dan faktor perilaku lain yang dapat memengaruhi konsumsi zat psikoaktif.

2. Penggunaan Data Longitudinal

   Mengumpulkan data secara longitudinal dapat membantu menangkap perubahan perilaku konsumsi zat seiring waktu dan faktor-faktor yang memengaruhinya, sehingga model dapat mempelajari pola temporal yang lebih kompleks.

3. Eksplorasi Model Prediktif yang Lebih Kompleks

   Walaupun model linear memberikan hasil yang relatif baik, penggunaan metode lain seperti model ensemble, deep learning, atau model yang dapat menangkap interaksi non-linear antar fitur dapat dieksplorasi, terutama jika didukung dengan data yang lebih kaya.

4. Pendekatan Kualitatif

   Penelitian kualitatif untuk menggali alasan dan motivasi individu dalam mengonsumsi zat dapat memberikan wawasan yang lebih dalam untuk memperbaiki pemilihan variabel dan model prediktif.

# **Daftar Pustaka**

[Castaneda, J., Calvet, L., Benito, S., Tondar, A., & Juan, A. A. (2022). Data science, analytics and artificial intelligence in e-health: Trends, applications and challenges. Idescat.](https://www.idescat.cat/sort/sort471/47.1.1.Castaneda-etal.pdf)

[Fehrman, E., Egan, V., & Mirkes, E. (2015). Drug consumption (quantified) [Data set]. UCI Machine Learning Repository. https://archive.ics.uci.edu/ml/datasets/Drug+consumption+(quantified)](https://arxiv.org/abs/1506.06297)

[Fernández-Suárez, Á., Pérez, V., & Martínez, F. (2024). Substance addiction in adolescents: Influence of parenting and personality traits. Brain Sciences, 14(5), 449. https://doi.org/10.3390/brainsci14050449](https://www.mdpi.com/2076-3425/14/5/449)

[Personality in alcohol and opioid use disorder: A multiphasic approach. (2024). Annals of Neurosciences. https://doi.org/10.1177/09727531241274098](https://journals.sagepub.com/doi/10.1177/09727531241274098)

[Tan, C. N.-L., & Fauzi, M. A. (2023). The significance of Big Data Analytics in Healthcare Information Systems. International Journal of Data Science and Big Data Analytics, 3(1), 45–57.](https://www.svedbergopen.com/files/1698407561_3_IJDSBDA202313011740NZ_(p_45-57).pdf)

[Volkow, N. D., Koob, G. F., & McLellan, A. T. (2023). Substance use disorders: A comprehensive update of classification, epidemiology, neurobiology, and treatment. European Journal of Neuroscience. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10168177/](https://pmc.ncbi.nlm.nih.gov/articles/PMC10168177/)
"""